Repository AY2122S1-CS2103T-T09-3/tp, pull requests merged in 2021-11, with the labels that each got.

#207 Brian - PPP draft
  docs/team/skcheongbrian.md
Labels: type.AboutUs

#205 Update UG to address large numbers
  docs/UserGuide.md
Labels: bug, type.UG

#214 v1.4 Add Zhi Hao's PPP draft
  docs/team/tanjiaxian99.md
  docs/team/yttruire.md
Labels: type.AboutUs

#213 Fix error message for notes
  src/main/java/seedu/address/logic/commands/NoteCommand.java
Labels: bug

#212 Change reference to address book to CSBook
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: bug

#211 Fix wrong error message for edit command
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: bug

#215 V1.4 bugfix addassessment case sensitivity
  docs/UserGuide.md
Labels: bug, documentation

#216 V1.4 bugfix groupname case sensitivity
  docs/UserGuide.md
Labels: bug, documentation

#219 Update ModelManagerTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.testing

#221 V1.4 add testcases notecommand
  src/main/java/seedu/address/logic/commands/NoteCommand.java
  src/main/java/seedu/address/model/student/Note.java
  src/test/java/seedu/address/logic/commands/NoteCommandTest.java
  src/test/java/seedu/address/logic/parser/NoteCommandParserTest.java
  src/test/java/seedu/address/model/student/NoteTest.java
  src/test/java/seedu/address/testutil/AssessmentBuilder.java
  src/test/java/seedu/address/testutil/NoteBuilder.java
  src/test/java/seedu/address/testutil/TypicalNote.java
Labels: type.testing

#217 Remove g/ prefix from editcommand and add test cases
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/CsBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/group/Group.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteGroupCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/group/GroupTest.java
  src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/StudentUtil.java
  src/test/java/seedu/address/testutil/TypicalGroup.java
  src/test/java/seedu/address/testutil/TypicalGroups.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: bug, type.testing

#228 v1.4 Update UG
  docs/Gemfile.lock
  docs/UserGuide.md
  docs/images/add0.png
  docs/images/addJunWeiResult.png
  docs/images/addassessment0.png
  docs/images/addgroup0.png
  docs/images/changegroup0.png
  docs/images/clear0.png
  docs/images/delete0.png
  docs/images/deleteassessment0.png
  docs/images/deletegroup0.png
  docs/images/edit0.png
  docs/images/edit1.png
  docs/images/find0.png
  docs/images/help0.png
  docs/images/note0.png
  docs/images/viewgroup0.png
  docs/images/viewstudent0.png
Labels: type.UG, priority.medium
